// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9CutIwDiBVFC100ZULQWP4ZwBfOyQevE',
    appId: '1:92575585124:web:cad269b1dc33ba9bb76071',
    messagingSenderId: '92575585124',
    projectId: 'project-leading-31f7b',
    authDomain: 'project-leading-31f7b.firebaseapp.com',
    storageBucket: 'project-leading-31f7b.firebasestorage.app',
    measurementId: 'G-BSEY41EX04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOJqBO0s6oEofzlonHc2pbTzvL5VTjJk8',
    appId: '1:92575585124:android:a03972d77f2cc96cb76071',
    messagingSenderId: '92575585124',
    projectId: 'project-leading-31f7b',
    storageBucket: 'project-leading-31f7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQbaBzFA8slOgjkI6bjbXB7OvbyCgU-RA',
    appId: '1:92575585124:ios:707c5eca145ef34fb76071',
    messagingSenderId: '92575585124',
    projectId: 'project-leading-31f7b',
    storageBucket: 'project-leading-31f7b.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );
}
